live_connectors:
  - name: bybit_testnet
    type: ccxt
    exchange_id: bybit
    paper: true
    default_type: spot
    symbols:
      - "BTC/USDT"
      - "ETH/USDT"
      - "SOL/USDT"
      - "XRP/USDT"
      - "ADA/USDT"
      - "DOGE/USDT"
      - "AVAX/USDT"
      - "LINK/USDT"
      - "MATIC/USDT"
      - "APT/USDT"
      - "BNB/USDT"
      - "TRX/USDT"
      - "XLM/USDT"
      - "BCH/USDT"
      - "SUI/USDT"
      - "HBAR/USDT"
      - "LTC/USDT"
      - "SHIB/USDT"
      - "TON/USDT"
      - "MNT/USDT"
      - "CRO/USDT"
      - "AAVE/USDT"
      - "PEPE/USDT"
      - "NEAR/USDT"
      - "ETC/USDT"
      - "ONDO/USDT"
      - "ARB/USDT"
      - "ICP/USDT"
      - "ALGO/USDT"
      - "ATOM/USDT"
      - "VET/USDT"
      - "KAS/USDT"
      - "SEI/USDT"
      - "XDC/USDT"
      - "FIL/USDT"
      - "QNT/USDT"
      - "INJ/USDT"
      - "TIA/USDT"
      - "OP/USDT"
      - "GRT/USDT"
      - "IOTA/USDT"
    timeframe: "15m"
    htf_timeframe: "1h"

strategy:
  donchian_len: 20       # ← השם הנכון
  adx_min: 14
  rsi_buy: 55
  rsi_sell: 45

trade_manager:
  atr_k_sl: 1.5
  r1_R: 1.0
  r2_R: 2.0
  p1_pct: 0.5
  p2_pct: 0.5
  be_after_R: 0.8
  trail_atr_k: 1.2
  max_bars_in_trade: 48

portfolio:
  equity0: 100000
  risk_per_trade: 0.005      # 0.5% לסיכון לעסקה
  max_position_pct: 0.10     # לא יותר מ-10% הון בפוזיציה
