# ======================
# CONFIG: Bybit Testnet
# ======================

live_connectors:
  - name: bybit_testnet
    type: ccxt
    exchange_id: bybit
    paper: true
    default_type: spot
    symbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT"]
    timeframe: "1h"
    htf_timeframe: "4h"

portfolio:
  equity0: 100000.0
  risk_per_trade: 0.008
  max_position_pct: 0.25
  max_concurrent_positions: 5
  daily_loss_cap_R: -4.0
  cooldown_bars_after_loss: 2

strategy:
  donchian_len: 20
  rsi_len: 14
  rsi_long_max: 70
  rsi_short_min: 30
  adx_len: 14
  adx_min: 18

trade_manager:
  atr_k_sl: 1.8
  r1_R: 1.5
  p1_pct: 0.30
  r2_R: 3.0
  p2_pct: 0.30
  be_after_R: 1.0
  trail_k_before: 1.8
  trail_k_after: 1.2
  max_bars_in_trade: 120
  pyramiding: false
  add_unit_R: 1.25
  max_units: 3
