from abc import ABC, abstractmethod
from typing import Dict, Any
import pandas as pd

class BaseConnector(ABC):
    @abstractmethod
    def init(self): ...
    @abstractmethod
    def fetch_ohlcv(self, symbol, timeframe: str, limit: int = 600) -> pd.DataFrame: ...
    @abstractmethod
    def create_market_order(self, symbol, side: str, qty: float) -> Dict[str, Any]: ...
    @abstractmethod
    def get_precision(self, symbol) -> Dict[str, Any]: ...
    @abstractmethod
    def account_equity(self) -> float: ...
