live_connectors:
  - name: bybit_testnet
    type: ccxt
    exchange_id: bybit
    paper: true
    default_type: spot
    symbols:
      - "BTC/USDT"
      - "ETH/USDT"
      - "SOL/USDT"
      - "XRP/USDT"
      - "ADA/USDT"
    timeframe: "1m"     # קצר יותר כדי לראות יותר אירועים
    htf_timeframe: "30m" # HTF קצר יחסית

strategy:
  donchian_len: 10      # היה 20 → עכשיו 10 כדי לקבל יותר פריצות
  adx_min: 8           # היה גבוה יותר → עכשיו 12 כדי לא לחסום יותר מדי

trade_manager:
  atr_k_sl: 0.8       # היה 1.2–1.5 → מקטין R → מגדיל כמות
  r1_R: 0.5
  r2_R: 1.0
  p1_pct: 0.5
  p2_pct: 0.5
  be_after_R: 0.5
  max_bars_in_trade: 30

portfolio:
  equity0: 100000
  risk_per_trade: 0.02   # 2% לעסקה (זמני כדי לקבל כניסה)
  max_position_pct: 0.50 # מאפשר יותר הון לעסקה (תקרת בטיחות)
