live_connectors:
  - name: bybit_testnet
    type: ccxt
    exchange_id: bybit
    paper: true
    default_type: spot
    symbols:
      - "AUTO"          # נשלוף אוטומטית את כל סימבולי USDT הפעילים
    timeframe: "1m"     # קצר – הרבה אירועים
    htf_timeframe: "5m" # HTF קצר – יותר סיגנלים

strategy:
  lenient_fallback: true   # מצב מקל – יוצר יותר סיגנלים
  donchian_len: 6          # קצר = יותר פריצות
  adx_min: 0               # מבטל חסימה של ADX

trade_manager:
  atr_k_sl: 0.8            # R קטן -> גודל פוזיציה גדול יותר
  r1_R: 0.5
  r2_R: 1.0
  p1_pct: 0.5
  p2_pct: 0.5
  be_after_R: 0.5
  max_bars_in_trade: 30

portfolio:
  equity0: 100000
  risk_per_trade: 0.02     # 2% כדי לראות כניסות
  max_position_pct: 0.50   # עד 50% הון לפוזיציה (תקרת בטיחות)
