live_connectors:
  - name: bybit_testnet
    type: ccxt
    exchange_id: bybit
    paper: true
    default_type: spot
    symbols: ["AUTO", "BTC/USDT", "ETH/USDT", "SOL/USDT", "XRP/USDT", "ADA/USDT"]  # AUTO + כמה גיבויים
    timeframe: "1m"
    htf_timeframe: "5m"

strategy:
  donchian_len: 4    # קצר כדי לייצר יותר פריצות
  adx_min: 0         # מבטל סינון ADX לבדיקות

trade_manager:
  atr_k_sl: 0.6
  r1_R: 0.4
  r2_R: 0.8
  p1_pct: 0.5
  p2_pct: 0.5
  be_after_R: 0.4
  max_bars_in_trade: 50

portfolio:
  equity0: 100000
  risk_per_trade: 0.03
  max_position_pct: 0.70
